doctrine:
    dbal:
        schema_filter: ~^(?!event)~ # this will ignore broadway event store table
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
            datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
        mapping_types:
            uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Employee:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/mapping/employee'
                prefix: 'App\Employee'
                alias: App
            Delegation:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/mapping/delegation'
                prefix: 'App\Delegation'
                alias: App
